package com.myteam.proyectoprueba;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class objetoPrueba implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public objetoPrueba() {
    }




}