package com.myteam.proyectoprueba;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class objetoPrueba implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nombre;

	public objetoPrueba() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public objetoPrueba(java.lang.String nombre) {
		this.nombre = nombre;
	}

}