package com.myteam.pruebafront;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosPrueba implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DatosPrueba() {
    }




}