package com.bbva.mfad.pymes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Productos implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Productos() {
    }




}