package com.bbva.mfad.pymes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Productos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String folioProducto;
	private java.lang.String estado;

	public Productos() {
	}

	public java.lang.String getFolioProducto() {
		return this.folioProducto;
	}

	public void setFolioProducto(java.lang.String folioProducto) {
		this.folioProducto = folioProducto;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public Productos(java.lang.String folioProducto, java.lang.String estado) {
		this.folioProducto = folioProducto;
		this.estado = estado;
	}

}