package com.bbva.mfad.pymes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Riesgos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String riesgoComercial;
	private java.lang.String riesgoPotencial;

	public Riesgos() {
	}

	public java.lang.String getRiesgoComercial() {
		return this.riesgoComercial;
	}

	public void setRiesgoComercial(java.lang.String riesgoComercial) {
		this.riesgoComercial = riesgoComercial;
	}

	public java.lang.String getRiesgoPotencial() {
		return this.riesgoPotencial;
	}

	public void setRiesgoPotencial(java.lang.String riesgoPotencial) {
		this.riesgoPotencial = riesgoPotencial;
	}

	public Riesgos(java.lang.String riesgoComercial,
			java.lang.String riesgoPotencial) {
		this.riesgoComercial = riesgoComercial;
		this.riesgoPotencial = riesgoPotencial;
	}

}